# Generated by Django 5.2.3 on 2025-09-27 09:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'bookmark',
                'verbose_name_plural': 'bookmarks',
            },
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'resource category',
                'verbose_name_plural': 'resource categories',
            },
        ),
        migrations.CreateModel(
            name='StudyResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('resource_type', models.CharField(choices=[('text', 'Text Notes'), ('audio', 'Audio Recording'), ('video', 'Video Recording'), ('pdf', 'PDF Document')], default='text', max_length=20, verbose_name='resource type')),
                ('file', models.FileField(blank=True, null=True, upload_to='study_resources/', verbose_name='file')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('institutional', 'Institutional')], default='public', max_length=20, verbose_name='access level')),
                ('access_cost', models.PositiveIntegerField(default=0, verbose_name='access cost')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='resource_thumbnails/', verbose_name='thumbnail')),
                ('transcript', models.TextField(blank=True, verbose_name='transcript')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration (seconds)')),
            ],
            options={
                'verbose_name': 'study resource',
                'verbose_name_plural': 'study resources',
                'ordering': ['-created_at'],
            },
        ),
    ]
