# Generated by Django 5.2.3 on 2025-09-27 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study', '0001_initial'),
        ('trends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studyresource',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studyresource',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trends.educationlevel', verbose_name='education level'),
        ),
        migrations.AddField(
            model_name='studyresource',
            name='skill_domains',
            field=models.ManyToManyField(blank=True, to='trends.skilldomain', verbose_name='skill domains'),
        ),
        migrations.AddField(
            model_name='studyresource',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='trends.subject'),
        ),
        migrations.AddField(
            model_name='studyresource',
            name='topics',
            field=models.ManyToManyField(blank=True, to='trends.topic'),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='resources',
            field=models.ManyToManyField(blank=True, to='study.studyresource'),
        ),
        migrations.AddField(
            model_name='resourcebookmark',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.studyresource'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcebookmark',
            unique_together={('user', 'resource')},
        ),
    ]
