# Generated by Django 5.2.3 on 2025-09-27 09:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='semester name')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='order')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('credits', models.PositiveIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EducationalSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='system name')),
                ('system_type', models.CharField(choices=[('pre_school', 'Pre-School'), ('primary', 'Primary School'), ('secondary', 'Secondary School'), ('vocational', 'Vocational Training'), ('university', 'University'), ('other', 'Other')], default='secondary', max_length=20, verbose_name='system type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_systems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('institution_type', models.CharField(choices=[('educational', 'Educational Institution'), ('medical', 'Medical Institution'), ('corporate', 'Corporate Organization'), ('government', 'Government Agency'), ('religious', 'Religious Organization'), ('community', 'Community Organization'), ('other', 'Other')], default='educational', max_length=20, verbose_name='institution type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('subdomain', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='subdomain')),
                ('custom_domain', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='custom domain')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approved')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='institution_banners/')),
                ('primary_color', models.CharField(default='#8b0000', max_length=7)),
                ('secondary_color', models.CharField(default='#f0f2f5', max_length=7)),
                ('allow_user_registration', models.BooleanField(default=True, verbose_name='allow user registration')),
                ('require_domain_email', models.BooleanField(default=False, verbose_name='require domain email')),
                ('allowed_email_domains', models.CharField(blank=True, max_length=500, verbose_name='allowed email domains')),
                ('user_limit', models.PositiveIntegerField(default=100, verbose_name='user limit')),
                ('storage_quota_mb', models.PositiveIntegerField(default=1024, verbose_name='storage quota (MB)')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_institutions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='level name')),
                ('level_type', models.CharField(choices=[('grade', 'Grade'), ('year', 'Year'), ('stage', 'Stage'), ('form', 'Form'), ('program', 'Degree Program'), ('course', 'Course'), ('semester', 'Semester')], default='grade', max_length=20, verbose_name='level type')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approved')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_levels', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='trends.educationlevel')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levels', to='trends.educationalsystem')),
                ('institution_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_levels', to='trends.institution')),
            ],
            options={
                'ordering': ['system', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('global_role', models.CharField(choices=[('participant', 'Participant'), ('setter', 'Setter'), ('admin', 'Admin'), ('institution_admin', 'Institution Admin'), ('institution_manager', 'Institution Manager'), ('institution_user', 'Institution User'), ('teacher', 'Teacher'), ('student', 'Student'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('staff', 'Staff')], default='participant', max_length=20)),
                ('institution_role', models.CharField(blank=True, choices=[('participant', 'Participant'), ('setter', 'Setter'), ('admin', 'Admin'), ('institution_admin', 'Institution Admin'), ('institution_manager', 'Institution Manager'), ('institution_user', 'Institution User'), ('teacher', 'Teacher'), ('student', 'Student'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('staff', 'Staff')], max_length=20, null=True)),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='trends.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='program name')),
                ('duration', models.PositiveSmallIntegerField(default=4, verbose_name='duration in years')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approved')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programs', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='trends.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='domain name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_skill_domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillSubdomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='subdomain name')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approved')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_skill_subdomains', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdomains', to='trends.skilldomain')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='space name')),
                ('space_type', models.CharField(choices=[('classroom', 'Classroom'), ('laboratory', 'Laboratory'), ('office', 'Office'), ('meeting_room', 'Meeting Room'), ('ward', 'Hospital Ward'), ('operating_theater', 'Operating Theater'), ('consultation_room', 'Consultation Room'), ('common_area', 'Common Area'), ('other', 'Other')], max_length=20, verbose_name='space type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='capacity')),
                ('equipment', models.TextField(blank=True, help_text='Available equipment or resources', verbose_name='equipment')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='building')),
                ('floor', models.CharField(blank=True, max_length=50, verbose_name='floor')),
                ('room_number', models.CharField(blank=True, max_length=20, verbose_name='room number')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('available_from', models.TimeField(blank=True, null=True, verbose_name='available from')),
                ('available_to', models.TimeField(blank=True, null=True, verbose_name='available to')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_spaces', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='trends.institution')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_spaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['building', 'floor', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='subject name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approved')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subjects', to=settings.AUTH_USER_MODEL)),
                ('education_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='trends.educationlevel')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='trends.institution')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='trends.semester')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='topic name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approved')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_topics', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='trends.subject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('trend_type', models.CharField(choices=[('class_schedule', 'Class Schedule'), ('surgery_schedule', 'Surgery Schedule'), ('meeting_schedule', 'Meeting Schedule'), ('work_shift', 'Work Shift'), ('appointment', 'Appointment'), ('event', 'Event')], default=True, max_length=20, verbose_name='trend type')),
                ('start_time', models.DateTimeField(default=True, verbose_name='start time')),
                ('end_time', models.DateTimeField(null=True, verbose_name='end time')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='recurring')),
                ('recurrence_pattern', models.CharField(blank=True, max_length=50, verbose_name='recurrence pattern')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_approved', models.BooleanField(default=True, verbose_name='approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='trends.institution')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organized_trends', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='participating_trends', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='trends.space')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='year name')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='order')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='trends.program')),
            ],
            options={
                'ordering': ['program', 'order'],
            },
        ),
        migrations.AddField(
            model_name='semester',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='trends.year'),
        ),
        migrations.AddConstraint(
            model_name='institution',
            constraint=models.UniqueConstraint(condition=models.Q(('subdomain__isnull', False)), fields=('subdomain',), name='unique_subdomain'),
        ),
        migrations.AddConstraint(
            model_name='institution',
            constraint=models.UniqueConstraint(condition=models.Q(('custom_domain__isnull', False)), fields=('custom_domain',), name='unique_custom_domain'),
        ),
        migrations.AlterUniqueTogether(
            name='skillsubdomain',
            unique_together={('domain', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='space',
            unique_together={('institution', 'name')},
        ),
        migrations.AddIndex(
            model_name='trend',
            index=models.Index(fields=['institution', 'start_time'], name='trends_tren_institu_4ead98_idx'),
        ),
        migrations.AddIndex(
            model_name='trend',
            index=models.Index(fields=['space', 'start_time'], name='trends_tren_space_i_de7f6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='year',
            unique_together={('program', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('year', 'name')},
        ),
    ]
