# Generated by Django 5.2.3 on 2025-10-01 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specialization',
        ),
        migrations.AddField(
            model_name='profile',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trends.year', verbose_name='academic year'),
        ),
        migrations.AddField(
            model_name='profile',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trends.educationlevel', verbose_name='education level'),
        ),
        migrations.AddField(
            model_name='profile',
            name='education_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trends.educationalsystem', verbose_name='education system'),
        ),
        migrations.AddField(
            model_name='profile',
            name='institution_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='institution_logo',
            field=models.ImageField(blank=True, null=True, upload_to='institution_logos/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='institution_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trends.program', verbose_name='degree program'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('participant', 'Participant'), ('setter', 'Setter'), ('admin', 'Admin'), ('institution_admin', 'Institution Admin'), ('institution_manager', 'Institution Manager'), ('institution_user', 'Institution User'), ('teacher', 'Teacher'), ('student', 'Student'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('staff', 'Staff')], default='participant', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='space_type',
            field=models.CharField(choices=[('study', 'Study Space'), ('interview', 'Interview Space'), ('meeting', 'Meeting Space')], max_length=20, verbose_name='space type'),
        ),
    ]
