# Generated by Django 5.2.3 on 2025-10-01 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0002_remove_profile_department_remove_profile_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='space',
            name='building',
        ),
        migrations.RemoveField(
            model_name='space',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='space',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='space',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='space',
            name='room_number',
        ),
        migrations.AddField(
            model_name='space',
            name='access_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='access code'),
        ),
        migrations.AddField(
            model_name='space',
            name='meeting_link',
            field=models.URLField(blank=True, verbose_name='meeting link'),
        ),
        migrations.AddField(
            model_name='space',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='supervised_spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='space',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for easy searching', max_length=200, verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='space',
            name='capacity',
            field=models.PositiveIntegerField(default=10, verbose_name='capacity'),
        ),
    ]
