# exams/constants.py

# Question Types
QUESTION_TYPE_MCQ = 'MCQ'
QUESTION_TYPE_TEXT = 'TEXT'
QUESTION_TYPE_CHOICES = [
    (QUESTION_TYPE_MCQ, 'Multiple Choice Question'),
    (QUESTION_TYPE_TEXT, 'Text Answer Question'),
]

# Exam Set Types
EXAM_SET_TYPE_FREE = 'FREE'
EXAM_SET_TYPE_PREMIUM = 'PREMIUM'
EXAM_SET_TYPE_REWARD = 'REWARD'
EXAM_SET_TYPE_CHOICES = [
    (EXAM_SET_TYPE_FREE, 'Free'),
    (EXAM_SET_TYPE_PREMIUM, 'Premium'),
    (EXAM_SET_TYPE_REWARD, 'Rewarded'),
]

# Attempt Statuses
ATTEMPT_STATUS_IN_PROGRESS = 'IN_PROGRESS'
ATTEMPT_STATUS_SUBMITTED = 'SUBMITTED'
ATTEMPT_STATUS_AUTO_SUBMITTED = 'AUTO_SUBMITTED'
ATTEMPT_STATUS_GRADING_PENDING = 'GRADING_PENDING'
ATTEMPT_STATUS_GRADED = 'GRADED'
ATTEMPT_STATUS_CHOICES = [
    (ATTEMPT_STATUS_IN_PROGRESS, 'In Progress'),
    (ATTEMPT_STATUS_SUBMITTED, 'Submitted'),
    (ATTEMPT_STATUS_AUTO_SUBMITTED, 'Auto Submitted'),
    (ATTEMPT_STATUS_GRADING_PENDING, 'Grading Pending'),
    (ATTEMPT_STATUS_GRADED, 'Graded'),
]

# Grading Choices
GRADING_CORRECT = 'CORRECT'
GRADING_INCORRECT = 'INCORRECT'
GRADING_CHOICES = [
    (GRADING_CORRECT, 'Correct'),
    (GRADING_INCORRECT, 'Incorrect'),
]